.TH LXQT-RUNNER "1" "January 2025" "LXQt\ 2.1.0" "LXQt\ Module"
.SH NAME
lxqt-runner \- Application launcher module of \fBLXQt\fR, the Lightweight Desktop
Environment
.SH SYNOPSIS
.B lxqt-runner
.br
.SH DESCRIPTION
This module allows to launch any application by typing the configured shortcut,
offers quick access to logout, shutdown and other functions. A calculator is also
implemented: e.g 2*4+10/2=.
.SH BEHAVIOR
As you type, suggestions will appear. Once the application you wish to run appears
you can navigate to it using the mouse or arrow keys on your keyboard.
Pressing enter or clicking the application will be launched. The activation shortcut
can be changed by the configuration menu, \fBlxqt-globalkeyshortcuts\fR (X11) or
in the compositor (Wayland).
.SH AUTOSTART
This module is only shown in the \fBLXQt\fR desktop environment but can be used
in other dsktop environments by adding it to autostart.
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt-runner/issues
.SH "SEE ALSO"
\fBLXQt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface, also intended for less powerful machines. See also:
.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-session(1)\fR
.P
\fBlxqt-config-session(1)\fR
.P
